name: Build 3DS CIA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをクローン
      uses: actions/checkout@v3

    - name: devkitPro toolchain のセットアップ
      run: |
        sudo apt update
        sudo apt install -y wget gnupg
        sudo wget https://apt.devkitpro.org/install-devkitpro-pacman
        echo | bash install-devkitpro-pacman
        sudo dkp-pacman -Sy --noconfirm
        sudo dkp-pacman -S --noconfirm devkitARM 3ds-dev 3ds-libcurl

    - name: devkitPro 環境変数を設定
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV

    - name: ビルドを実行
      run: |
        make

    - name: 成果物をアップロード（.cia）
      uses: actions/upload-artifact@v4
      with:
        name: mikann-downloader-cia
        path: |
          build/*.cia
