name: Build Mikann File Downloader CIA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン（Actions内では不要だが安全のため）
      - name: Checkout repository
        uses: actions/checkout@v4

      # pacman インストーラーをダウンロード
      - name: Download devkitPro pacman installer
        run: wget -O $HOME/install-devkitpro-pacman https://raw.githubusercontent.com/enswapwar/mikann-file-downloader/main/tools/install-devkitpro-pacman

      # 実行権限を付与
      - name: Make installer executable
        run: chmod +x $HOME/install-devkitpro-pacman

      # pacman インストール
      - name: Install devkitPro pacman
        run: sudo $HOME/install-devkitpro-pacman

      # 必要なツールを pacman 経由でインストール
      - name: Install devkitARM and ctrulib
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM ctrulib

      # 環境変数を設定
      - name: Set environment variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "PATH=/opt/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_ENV

      # Build フォルダ作成
      - name: Create build directory
        run: mkdir -p build

      # CIA ビルド
      - name: Build CIA
        run: make all

      # アーティファクトとして出力
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/*.cia
