name: Build 3DS CIA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-cia:
    runs-on: ubuntu-latest

    env:
      DEVKITPRO: ${{ github.workspace }}/devkitpro
      DEVKITARM: ${{ github.workspace }}/devkitpro/devkitARM
      PATH: ${{ github.workspace }}/devkitpro/devkitARM/bin:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y wget bzip2 tar make

    - name: Setup devkitARM
      run: |
        mkdir -p $DEVKITPRO
        cd $DEVKITPRO
        # 最新の devkitARM r47 以降の tar.bz2 直ダウンロードURLに置き換えてください
        wget -O devkitARM.tar.bz2 https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r47/devkitARM_r47-linux.tar.bz2 || true
        tar -xjf devkitARM.tar.bz2
        ls -l $DEVKITARM/bin

    - name: Setup ctrulib
      run: |
        mkdir -p $DEVKITPRO/portlibs
        curl -L https://github.com/devkitPro/ctrulib/archive/refs/heads/master.tar.gz | tar xz -C $DEVKITPRO/portlibs --strip-components=1

    - name: Build CIA
      run: |
        mkdir -p build
        make all
        ls -l build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cia-artifacts
        path: build/*.cia
