name: Build 3DS Downloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget unzip p7zip-full libpng16-16 libqrencode4 qrencode

      - name: Download makerom
        run: |
          wget -O makerom.zip https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.3/makerom-v0.18.3-ubuntu_x86_64.zip
          unzip makerom.zip -d makerom-bin
          chmod +x makerom-bin/makerom

      - name: Download 3ds-bannertool
        run: |
          wget -O bannertool.zip https://github.com/carstene1ns/3ds-bannertool/archive/refs/tags/1.2.1.zip
          unzip bannertool.zip
          cd 3ds-bannertool-1.2.1
          mkdir -p build
          cd build
          cmake ..
          make
          sudo mv bannertool /usr/local/bin

      - name: Build mikann-file-downloader
        run: |
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikann-file-downloader
          path: |
            build/*.cia
            makerom-bin/makerom
            /usr/local/bin/bannertool
