name: Build CIA

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qrencode p7zip-full
          curl -L https://github.com/Steveice10/bannertool/releases/download/1.2.0/bannertool.zip -o bannertool.zip
          7z e bannertool.zip linux-x86_64/bannertool
          chmod +x bannertool
          sudo mv bannertool /usr/local/bin
          curl -L https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.18.3/makerom-v0.18.3-ubuntu_x86_64.zip -o makerom.zip
          7z e makerom.zip
          chmod +x makerom
          sudo mv makerom /usr/local/bin

      - name: Build project
        run: |
          make
          bannertool makesmdh -s "Mikann Downloader" -l "mikann" -p "enswapwar" -i assets/icon.png -o icon.icn
          makerom -f cia -o mikann-downloader.cia -rsf meta.rsf -target t -elf build/mikann-downloader.elf -icon icon.icn

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/*.elf
            build/*.3dsx
            build/*.cia
            icon.icn

      - name: Publish pre-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Build"
          files: |
            build/*.cia
            build/*.elf
            build/*.3dsx
