name: Build 3DS Cia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt update
        sudo apt install -y git curl unzip build-essential
    - run: |
        curl -L https://devkitpro.org/devkitpro-pacman/install-devkitpro-pacman.sh -o install-devkitpro-pacman.sh
        chmod +x install-devkitpro-pacman.sh
        sudo ./install-devkitpro-pacman.sh
    - run: |
        echo "export DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "export PATH=/opt/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_ENV
    - run: make
