name: Build Mikann File Downloader CIA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 必要なツールをインストール
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tar unzip wget build-essential git python3 python3-pip

      # devkitPro の pacman スクリプト取得とインストール
      - name: Install devkitPro
        run: |
          DEVKITPRO=$HOME/devkitpro
          DEVKITARM=$DEVKITPRO/devkitARM
          mkdir -p $DEVKITPRO
          wget -O $DEVKITPRO/install-devkitpro-pacman https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x $DEVKITPRO/install-devkitpro-pacman
          $DEVKITPRO/install-devkitpro-pacman --noninteractive
          echo "export DEVKITPRO=$DEVKITPRO" >> $GITHUB_ENV
          echo "export DEVKITARM=$DEVKITARM" >> $GITHUB_ENV
          echo "export PATH=$DEVKITARM/bin:$DEVKITPRO/tools/bin:$PATH" >> $GITHUB_ENV

      # ctrulib をクローン
      - name: Clone ctrulib
        run: |
          mkdir -p $DEVKITPRO/portlibs
          git clone --depth=1 https://github.com/devkitPro/ctrulib.git $DEVKITPRO/portlibs/ctrulib

      # build ディレクトリ作成
      - name: Create build directory
        run: mkdir -p build

      # CIA をビルド
      - name: Build CIA
        run: make all

      # ビルド成果物をアップロード
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikann-file-downloader-build
          path: |
            build/*.cia
            build/*.3dsx
            build/*.elf
