name: Build 3DS CIA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget tar bzip2 python3-pip

      - name: Install devkitARM
        run: |
          mkdir -p $HOME/devkitpro
          cd $HOME/devkitpro
          wget https://github.com/devkitPro/devkitarm/releases/download/v60/devkitARM_r60-x86_64-linux.tar.xz
          tar -xf devkitARM_r60-x86_64-linux.tar.xz
          mv devkitARM $DEVKITARM
          echo "$DEVKITARM/bin" >> $GITHUB_PATH

      - name: Install 3ds tools
        run: |
          sudo apt-get install -y makerom 2>/dev/null || true
          if ! command -v makerom >/dev/null; then
            git clone https://github.com/3DSGuy/Project_CTR.git
            cd Project_CTR/makerom && make && sudo cp makerom /usr/local/bin/
          fi

      - name: Ensure meta.rsf exists
        run: |
          if [ ! -f meta.rsf ]; then
            cat > meta.rsf <<'EOF'
BasicInfo:
  Title                   : "Mikann File Downloader"
  ProductCode             : "CTR-P-MIKN"
  UniqueId                : 0x12345
SystemControlInfo:
  SaveDataSize            : 0KB
  RemasterVersion         : 1
EOF
          fi

      - name: Build CIA
        run: |
          mkdir -p build
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cia-build
          path: build/*.cia
