name: Build 3DS CIA

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # devkitARM/bin を PATH に通す（これが無いと arm-none-eabi-gcc が見つからない）
      - name: Add devkitPro toolchains to PATH
        run: |
          echo "$DEVKITARM/bin" >> "$GITHUB_PATH"
          echo "$DEVKITPRO/tools/bin" >> "$GITHUB_PATH"

      # デバッグ用（壊れたらログ見りゃ一発）
      - name: Verify toolchain exists
        run: |
          echo "DEVKITPRO=$DEVKITPRO"
          echo "DEVKITARM=$DEVKITARM"
          ls -l "$DEVKITARM/bin" || true
          which arm-none-eabi-gcc || true

      # meta.rsf が無い場合だけ最小構成を生成（YAML事故回避のため printf で書く）
      - name: Ensure meta.rsf
        run: |
          if [ ! -f meta.rsf ]; then
            printf '%s\n' \
'BasicInfo:' \
'  Title                   : "Mikann File Downloader"' \
'  ProductCode             : "CTR-P-MIKN"' \
'  UniqueId                : 0x12345' \
'SystemControlInfo:' \
'  SaveDataSize            : 0KB' \
'  RemasterVersion         : 1' \
'AccessControlInfo:' \
'  EnableL2Cache           : true' \
> meta.rsf
          fi

      - name: Build
        run: |
          make -j2

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          cp -f build/*.elf  artifacts/ 2>/dev/null || true
          cp -f build/*.3dsx artifacts/ 2>/dev/null || true
          cp -f build/*.cia  artifacts/ 2>/dev/null || true
          cp -f ./*.cia      artifacts/ 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikann-build
          path: artifacts
