name: Build CIA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build CIA
        run: |
          make
          mkdir -p artifacts
          cp build/*.cia artifacts/ || true
          cp build/*.elf artifacts/ || true
          cp build/*.3dsx artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikann-build
          path: artifacts/*
