name: Build CIA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git cmake libpng-dev pkg-config

    - name: Setup devkitPro
      run: |
        sudo mkdir -p /opt/devkitpro
        cd /opt/devkitpro
        git clone https://github.com/devkitPro/pacman.git
        cd pacman
        sudo make install

    - name: Setup env
      run: |
        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "/opt/devkitpro/devkitARM/bin" >> $GITHUB_PATH

    - name: Build
      run: |
        make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cia-build
        path: build/*
