# .github/workflows/build.yml
name: Build 3DS CIA

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget unzip tar build-essential git cmake p7zip-full python3

      - name: Install devkitPro pacman
        run: |
          mkdir -p /opt/devkitpro
          wget https://downloads.devkitpro.org/devkitpro-pacman-x86_64.tar.xz
          tar -xf devkitpro-pacman-x86_64.tar.xz -C /opt/devkitpro
          export DEVKITPRO=/opt/devkitpro
          export PATH=$DEVKITPRO/tools/bin:$PATH
          pacman -Syu --noconfirm
          pacman -S --noconfirm devkitARM

      - name: Build 3DS BannerTool
        run: |
          wget https://github.com/carstene1ns/3ds-bannertool/archive/refs/tags/1.2.1.zip -O bannertool.zip
          unzip bannertool.zip
          mkdir -p build
          cd 3ds-bannertool-1.2.1
          mkdir build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$DEVKITPRO/devkitARM.cmake
          make -j$(nproc)
          cd ../../
          cp 3ds-bannertool-1.2.1/build/bannertool ./build/

      - name: Build CIA
        run: |
          mkdir -p build/cia
          $DEVKITPRO/tools/bin/makerom -f cia -o build/cia/output.cia -d assets content/

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: cia
          path: build/cia/output.cia
