name: Build Mikann File Downloader CIA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVKITPRO: ${{ runner.temp }}/devkitpro
      DEVKITARM: ${{ runner.temp }}/devkitpro/devkitARM
      PATH: ${{ runner.temp }}/devkitpro/devkitARM/bin:${{ runner.temp }}/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      # コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 必要なツールをインストール (tar, wget など)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tar unzip wget build-essential git python3 python3-pip

      # devkitPro を取得して展開
      - name: Download devkitPro
        run: |
          mkdir -p $DEVKITPRO
          wget -O $DEVKITPRO/install-devkitpro-pacman https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x $DEVKITPRO/install-devkitpro-pacman
          $DEVKITPRO/install-devkitpro-pacman --noninteractive

      # ctrulib (3DS 用ライブラリ) を取得
      - name: Clone ctrulib
        run: |
          mkdir -p $DEVKITPRO/portlibs
          git clone --depth=1 https://github.com/devkitPro/ctrulib.git $DEVKITPRO/portlibs/ctrulib

      # build ディレクトリ作成
      - name: Create build directory
        run: mkdir -p build

      # CIA をビルド
      - name: Build CIA
        run: make all

      # ビルド成果物をアップロード
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mikann-file-downloader-build
          path: |
            build/*.cia
            build/*.3dsx
            build/*.elf
