name: Build 3DS CIA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-cia:
    runs-on: ubuntu-latest
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM
      PATH: /opt/devkitpro/devkitARM/bin:${{ github.workspace }}/bin:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential unzip wget git python3 python3-pip

    - name: Download prebuilt devkitPro
      run: |
        wget -O devkitpro.zip https://github.com/enswapwar/mikann-file-downloader/releases/download/v1/devkitpro.zip
        sudo unzip -o devkitpro.zip -d /opt
        rm devkitpro.zip

    - name: Verify devkitARM
      run: |
        echo "DEVKITARM=$DEVKITARM"
        $DEVKITARM/bin/arm-none-eabi-gcc --version

    - name: Build CIA
      run: |
        mkdir -p build
        make all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cia-artifacts
        path: |
          build/*.cia
          build/*.3dsx
          build/*.elf
