name: Build 3DS CIA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wget tar bzip2 make git

      - name: Download devkitARM
        run: |
          mkdir -p $HOME/devkitpro
          wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r47/devkitARM_r47-linux.tar.bz2
          tar -xjf devkitARM_r47-linux.tar.bz2 -C $HOME/devkitpro
          echo "DEVKITPRO=$HOME/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=$HOME/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "$HOME/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_PATH

      - name: Download ctrulib
        run: |
          git clone --depth=1 https://github.com/devkitPro/ctrulib.git $HOME/devkitpro/portlibs/ctrulib

      - name: Make build directory
        run: mkdir -p build

      - name: Build CIA
        run: make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cia-build
          path: build/
