name: Build Mikann File Downloader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget tar bzip2 zip make cmake

    - name: Install devkitPro
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm devkitARM 3ds-dev

    - name: Set environment
      run: |
        echo "export DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "export PATH=$DEVKITARM/bin:$PATH" >> $GITHUB_ENV

    - name: Build Cia
      run: |
        mkdir -p build
        make all

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cia-artifacts
        path: |
          build/*.cia
          build/*.3dsx
          build/*.elf
