name: Build 3DS Cia

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: 基本パッケージインストール
      run: |
        sudo apt update
        sudo apt install -y git curl unzip build-essential

    - name: devkitPro pacman を直接インストール
      run: |
        curl -L https://github.com/devkitPro/pacman/releases/download/v0.12.7/pacman-v0.12.7-linux.zip -o pacman.zip
        unzip pacman.zip -d pacman
        sudo ./pacman/install.sh

    - name: パスを通す
      run: |
        echo "export DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "export DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
        echo "export PATH=/opt/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_ENV

    - name: ビルド
      run: make
