name: Build 3DS CIA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install -y wget unzip tar bzip2 make

    - name: Download and install devkitPro pacman
      run: |
        wget https://github.com/devkitPro/pacman/releases/download/v6.0.2/devkitpro-pacman-amd64.deb
        sudo dpkg -i devkitpro-pacman-amd64.deb
        sudo dkp-pacman -Syu --noconfirm
        sudo dkp-pacman -S --noconfirm devkitARM 3ds-dev

    - name: Add devkitPro to PATH
      run: |
        echo "export DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "export DEVKITARM=$DEVKITPRO/devkitARM" >> $GITHUB_ENV
        echo "export PATH=$DEVKITARM/bin:$PATH" >> $GITHUB_ENV

    - name: Build CIA
      run: |
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: 3ds-build
        path: build/
