name: Build CIA

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential

      - name: Install devkitPro pacman
        run: |
          wget https://github.com/devkitPro/pacman/releases/download/v6.0.2/devkitpro-pacman.amd64.deb
          sudo apt install ./devkitpro-pacman.amd64.deb

      - name: Install devkitARM
        run: |
          sudo dkp-pacman -Sy --noconfirm devkitARM 3ds-dev

      - name: Build CIA
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=$DEVKITPRO/devkitARM
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cia-build
          path: build/*
