name: Build 3DS CIA

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget make gcc g++ git unzip xz-utils build-essential python3

      - name: Install devkitPro
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Sy --noconfirm devkitARM general-tools 3ds-dev

      - name: Set environment variables
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "PATH=/opt/devkitpro/devkitARM/bin:$PATH" >> $GITHUB_ENV

      - name: Build project
        run: |
          make

      - name: Upload CIA artifact
        uses: actions/upload-artifact@v3
        with:
          name: 3ds-cia
          path: "*.cia"
